name: PHP CI/CD Pipeline

on:
  push:
    branches:
      - main
      - dev
      - feature/*

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Install dependencies
        run: composer install

      - name: Run tests
        run: vendor/bin/phpunit --testdox

  deploy-staging:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/dev'
    steps:
      - name: Simulate staging deployment
        run: echo "Deploying to STAGING server..."

  deploy-production:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Simulate production deployment
        run: echo "Deploying to PRODUCTION server..."
